### ISSUE TITLE
Default mouse click bindings

### ISSUE THREAD

**Issue by karlch** [karlch/vimiv-qt#136]
I personally don't use the mouse much, so I also don't know what sane mouse bindings for various widgets would be.

Library and thumbnail mode seem pretty much set. Maybe binding `<button-right>` in the library to `:scroll left` a.k.a. go to the parent directory, would make sense.

In image mode we may want to:
* Focus the next/previous
* Switch to thumbnail mode
* Switch to library mode
* ...

Input from anyone using the mouse more than me would be very helpful :smiley:

**Comment by BachoSeven** [comment]
Regarding the library bindings, `<button-right>` for parent directories makes sense to me; I also use that in `lf` for instance.

For image mode, I would suggest having `<button-right>` bound to switching to Library mode, since this is muscle memory I have from using `sxiv`.

Although most people only have a few mouse buttons, the most useful bindings for focusing the next/previous image are what `xev` reports as `Button 8` and `Button 9`, present on many mice as "Previous/Next" Buttons (i.e. used for navigating tab history in a browser). This could perhaps be configurable(?) 

Alternatively, one could use the scrolling wheel to focus the next image, but I think the scrolling wheel would be most suited to zooming in/out in Image mode.

**Comment by karlch** [comment]
Thanks a lot for your input, all of what you say makes sense to me. I will see if I can find a mouse with the corresponding buttons and test the next / prev stuff with them. Once done, I guess adding:
- `<button-right>` for parent directory in library mode
- `<button-right>` for entering the library in image mode
- `<button-8>` / `<button-9>` for switching images in image mode

as default bindings can just be done.

Note that mouse bindings are configurable in the `keys.conf` like any regular keys. A nice way to figure out the names of the bindings in vimiv is by launching vimiv with `--debug gui.eventhandler` as it spits out the event like:
```
[14:55:43] DEBUG    <gui.eventhandler>   EventHandlerMixin: handling <button-right> for mode image
```

I would also personally not touch the scrolling wheel for switching images. Like you say, it makes sense to use it for zooming. This is currently doable when using it while pressing `<ctrl>`. Without the modifier, it is used for scrolling the image in case it is zoomed.

**Comment by BachoSeven** [comment]
Thanks, I didn't notice `<ctrl>`+scroll-wheel was already implemented.

**Comment by karlch** [comment]
Took me a while, but the discussed bindings should have been added in 8c947261dd4ab93c437cfcc5b050813f5cdaa23a. Thanks again for your suggestions and let me know if you have more ideas / experience any issues :blush:

**Comment by BachoSeven** [comment]
Looks good to me! 
If anything, I just noticed that I mistakenly said `<button-right>` was supposed to be Library mode, but I really meant _Thumbnail_ mode, since I was talking about the analogue mode in Sxiv, where indeed right clicking opens the thumbnails.
That being said, the current behaviour also makes sense to me, and perhaps a good idea would be to add `<button-middle>` to open Thumbnail mode, so they're both covered, which is intuitive since Thumbnail mode is more "centered" than Thumbnail mode..

A minor issue: currently, in Library mode, buttons `Middle`, `Next` and `Previous` all behave in the same way as `<button-left>`. Perhaps next/prev could be bound to `:next` and `:prev` ;) and middle could be unbound by default in library mode.

**Comment by karlch** [comment]
Ah, yes, that of course also makes sense. I like your recommendation to use `<button-middle>` for thumbnail mode here though, how about then doing the same in library mode? So we would add:
- `<button-middle>` to enter thumbnail in image and library mode
- `<button-forward>` / `<button-back>` for `:next` / `:prev` in library mode (or the slightly more consistent `:scroll up/down --open-selected` which handles directories accordingly)

**Comment by BachoSeven** [comment]
Those sound perfect, especially the `:scroll up/down --open-selected` trick.

**Comment by karlch** [comment]
Nice, added in faf51bacc68efad17a5bd5681c3906835c15d233.

**Comment by BachoSeven** [comment]
I think it would make sense to have the scrolling wheel scroll up/down between images(without opening them) in Library mode

**Comment by karlch** [comment]
You mean changing the actual selection? What advantage does this have compared to just scrolling around and selecting a new path on demand?

I could see this being slightly smoother as the current behaviour of "centering the selected path" can lead to a bit of a funky jump when manually picking a path with the mouse. Is this the reasoning behind it?

**Comment by BachoSeven** [comment]
Uhm I had not noticed that, perhaps because I usually deal with small galleries or because have a big screen :'D

Then I think the current behaviour is fine, I thought scrolling was unmapped in library mode instead.

**Comment by karlch** [comment]
Closing as there should be a sufficient stack of mouse bindings for reasonable usage IMHO. Any further customization can go into its own issue as-needed.
