### ISSUE TITLE
Configuration inside CONFIG_HOME but plugins inside DATA_HOME?

### ISSUE THREAD

**Issue by scrouthtv** [karlch/vimiv-qt#210]
I was trying to write a small plugin for `vimiv` to provide two more statusbar modules, when I noticed that my user plugins aren't loaded (no error message whatsoever).

Upon further research I found out that `$XDG_CONFIG_HOME` (where configuration is placed) defaults to `~/.config/` **but** `$XDG_DATA_HOME` (where user plugins are placed) defaults to `~/.local/share/`.

This was my mistake. My question is, is it intended behavior that the plugins are located in a different folder than the configuration?

Thanks in advance :)

**Comment by karlch** [comment]
This is really cool, first time I hear from someone else testing the plugin system! :tada: 

The behaviour is intendend, I hope I can make my thought process clear:
* You can have multiple plugins installed or available in the data directory
* You can configure to activate only some of them

Thus I thought it would be a good idea to put the plugins in general into the data directory.

The problem here certainly is the "no error message whatsoever". I honestly don't know what I was thinking when I made the log message a debug message in `plugins.__init__` (l. 104), this is clearly an error. I will promote this to an error message and print out the directories in which the plugins are searched for there as well.

**Comment by scrouthtv** [comment]
Thanks for the feedback!

I am using i3 so windows most of the time aren't in their "natural" proportions and my statusbar gets crowded very quickly and I there's just too much information. The first thing I want to implement is a shortened `pwd` or `filename` which replaces parts of the filename with `...`.

Thanks for the awesome program! Closing for now.

**Comment by karlch** [comment]
Sounds useful!

As mentioned before I updated the log messages, I hope something like this
```
[12:13:11] ERROR    <plugins>            Unable to find plugin 'myplugin', ignoring.
    Available app plugins: 'demo', 'imageformats', 'print'
    Available user plugins: 'gphoto', 'mysettings'
    User plugin directory: '/home/user/.local/share/vimiv/plugins'
```
makes this much more discoverable.
