### ISSUE TITLE
Key conflicts displayed before parsing the entirety of keys.conf

### ISSUE THREAD

**Issue by schyzophrene-asynchrone** [karlch/vimiv-qt#270]
Issue #249 part 2!

Unbinding appropriate keys works, however, since warnings are displayed while parsing `keys.conf`, some of them are still displayed. Suppose I bind `t` before unbinding `ts` for example.

To solve this I could move all `unbind` statements up, but I have the case where I want to bind `s` in `[GLOBAL]`, so I need to unbind `sl`, `sh` and `ss` in `[IMAGE]`. I also have to put the `[IMAGE]` section before the `[GLOBAL]` section. But in `[GLOBAL]` I unbind `k` and bind `kl`, `kh` and `ks` in `[IMAGE]`, so no matter what I do I still have warnings.

The culprit is the `__setitem__` method of the `Trie` class in `vimiv/utils/trie.py`. It should not trigger a warning every time a binding is modified during startup, but wait for `keys.conf` to be totally read.

**Comment by karlch** [comment]
Thanks for the detailed report!

This makes perfect sense and will probably require some refactoring. An option could be to add a `Trie.check` function that triggers any remaining warnings instead of warning instantly in the `__setitem__` as you describe. This would then have to be called
- when `keys.conf` is totally read
- and when calling the `bind` command defined in `config.configcommands.py`.
