### ISSUE TITLE
Don't reset zoom level when reloading an image

### ISSUE THREAD

**Issue by petobens** [karlch/vimiv-qt#33]
Let's say I've opened an image and zoom in to say 200%. Now  if I modify that imagine from outside vimiv then vimiv correctly picks up the change but sets zoom level back to 100%. I believe the correct behaviour would be to respect the current zoom level and not reset it.

**Comment by karlch** [comment]
Makes perfect sense.

This happens because the working directory handler simply emits `new_image_opened` / images are reloaded as if they are new when the working directory handler emits changes. The signal handling should be improved and refined.

**Comment by petobens** [comment]
Ok. Thanks

**Comment by petobens** [comment]
Hi! Any updates on this? Thanks :)

**Comment by karlch** [comment]
Unfortunately not yet, I will look into it as soon as I can and some other issues of higher priority have been resolved. If you like, you can also give it a shot and I'll give you some more detail as on how I would try to approach this (and be the first contributor to the python code :tada: ). Otherwise it will just stay on the list of things todo soon :tm: , sorry for any inconvenience.

**Comment by karlch** [comment]
Let me know if this works for you :)

**Comment by petobens** [comment]
Seems to work great! Thank you!!
