### ISSUE TITLE
Scroll wheel zooming

### ISSUE THREAD

**Issue by ArtemSmaznov** [karlch/vimiv-qt#448]
I have looked through the documentation and the issues list here and can see that remapping mouse scroll wheel doesn't seem possible. I have seen than you can zoom in with the mouse if you hold down Ctrl, but I keep finding myself wishing I could do it with just the mouse's scroll wheel. I don't really care for panning the images with scroll wheels as you can just hold and drag.

If adding the ability to remap the scroll wheel for the mouse is not possible can an extra config parameter be added? Something like `mouse_only_zoom = False` by default but if set to `True` would remove the dependency for the Ctrl modifies for wheel scroll?

**Comment by karlch** [comment]
Thanks for your interest in vimiv!

Allowing to remap the scroll wheel to arbitrary commands is somewhat difficult as the step size usually needs to be customized to the corresponding command. An extra config parameter is trivial though. If all we need is a boolean to turn on and off the `<ctrl>` requirement, we just need another `BoolSetting` in `api.settings`, e.g. `image.wheel_zoom_ctrl`, and to check for the setting accordingly in the `wheelEvent` of `gui.image`. A slightly more flexible, but also more involved, option would be a setting that defines the required modifier(s), e.g. `image.zoom_wheel_modifier` which would default to `<ctrl>` but could be set to any modifier or none at all. This option also seems slightly more readible, unless we find a more descriptive setting name for the boolean version.

Any preferences here? Would you like to give it a shot and open a PR, otherwise I would probably take a more detailed look later this week.

**Comment by ArtemSmaznov** [comment]
Thanks for the quick response. Really enjoying Vimiv - been using it for a few months.
I think that `Ctrl` is what most people use when they prefer to keep the modifier in so it seems to me that simply adding the config to control whether a modifier is needed or not is enough. Especially if it brings more complexity. Unless there are others who want to use a different modifier. Personally, I would be happy with either one.

I am not familiar with the code base myself so would appreciate if you can give it a go whenever you have the time.

Thanks once again.

**Comment by karlch** [comment]
Just merged #449 which should implement the boolean toggle. Let me know in case I messed up :smile:

**Comment by ArtemSmaznov** [comment]
That was fast thanks, will test it out after work

**Comment by ArtemSmaznov** [comment]
@karlch tested this with both True and False and can confirm that both work as expected.
Library and Tiles still scroll with wheel as before. Also while having Library open with Image view the scroll wheel acts on the segment that is under cursor (meaning you don't have to change focus with the keyboard or click) which is a nice flow - I did not expect that to happen but happy that it did ;)

So all good and thanks once again - this was the only thing that was bothering me with Vimiv

**Comment by karlch** [comment]
Nice, thanks for testing and glad everything works as expected. Sometimes it helps to use a huge framework like Qt for the heavy lifting :grinning:
