### ISSUE TITLE
[Feature Request] Displaying `.ico` files

### ISSUE THREAD

**Issue by TornaxO7** [karlch/vimiv-qt#483]
It would be nice if `vimiv` could display `.ico` files.

**Comment by jcjgraf** [comment]
That should easily be doable using a plugin. I do not have the time to look into it myself, but if you want to give it a shot, I can assist you.

You need in essence two functions:
- `test_ico` which, given the header of a file, determines if this file is a ico.
    - You can inspect the header of a file using e.g. `xxd file.ico | head` or by printing the header from within your plugin.
- `load_ico` which, given an ico file, creates a QPixmap

Have a look at my [Raw](https://github.com/jcjgraf/RawPrev/blob/master/__init__.py) and [Video](https://github.com/jcjgraf/Video/blob/main/__init__.py) support plugin for an example. 

Let me know if you want to try it yourself and if you need any help.

**Comment by TornaxO7** [comment]
I have to do math at the moment, but I think that I can give it a shot later.

**Comment by TornaxO7** [comment]
I'm trying to get [the logging](https://github.com/TornaxO7/vimico/blob/main/__init__.py#L31) working, but I don't get any logs in my `~/.local/share/vimiv/vimiv.log` file. Is that normal?

By the way, I'm still using [your fork](https://github.com/karlch/vimiv-qt/issues/386) of vimiv :D

**Comment by jcjgraf** [comment]
Don't you get **ANY** logs in that file, or just no logs from your module? If you do not get anything, then it is probably because by default only a higher level  that debug is logged (like `info` or `warning`). Have you tried to run vimiv with `--log-level debug`?

This will print quite a lot of debug information. You can restrict the output to your module (/plugin) by using `--debug vimico` (or the name of your plugin) instead.

> By the way, I'm still using your fork of vimiv :D

Haha, shame on me. That is also something I should finish some time. Actually, only some unit tests are missing, but I am not very familiar with the testing package and currently I do not have the time to look into that :see_no_evil: 

Let me know if you need anything else

**Comment by TornaxO7** [comment]
> Have you tried to run vimiv with --log-level debug?

No, I didn't knew that this option exists xD Thank you! I'm getting some logs now :)

> This will print quite a lot of debug information. You can restrict the output to your module (/plugin) by using --debug vimico (or the name of your plugin) instead.

Thank you! That helps a lot!

**Comment by TornaxO7** [comment]
Ok, so the `.ico` files should be detected successfully now, but I've got a little problem with displaying the `.ico` files. What am doing wrong [here](https://github.com/TornaxO7/vimico/blob/main/__init__.py#L27)?

**Comment by jcjgraf** [comment]
`QImageReader` can only read [certain](https://doc.qt.io/qtforpython/PySide6/QtGui/QImageReader.html?highlight=qimagereader#PySide6.QtGui.PySide6.QtGui.QImageReader.supportedImageFormats) file types, and `ICO` is not among them (otherwise vimiv would be able to ready them by default).
What I did in my two plugins is, I use some other utility to convert the raw/video file into a jpg, which then can be read using `QImageReader`. The `QImageReader` is then converted to a `QPixmap`.

There is also [QIcon](https://doc.qt.io/qtforpython/PySide6/QtGui/QIcon.html?highlight=qicon#PySide6.QtGui.PySide6.QtGui.QIcon) which may be able to read ico files. If so, you need to also check if there is a way to create e `QPixmap` out of that.

Hope this helps.

**Comment by TornaxO7** [comment]
> QImageReader can only read [certain](https://doc.qt.io/qtforpython/PySide6/QtGui/QImageReader.html?highlight=qimagereader#PySide6.QtGui.PySide6.QtGui.QImageReader.supportedImageFormats) file types, and ICO is not among them (otherwise vimiv would be able to ready them by default).

Welp, that makes sense

> What I did in my two plugins is, I use some other utility to convert the raw/video file into a jpg, which then can be read using QImageReader. The QImageReader is then converted to a QPixmap.

Ooooh, that explains your `QProcess`! Nice, I'll look into it. Thanks!

**Comment by TornaxO7** [comment]
Hm... I'm a little bit confused: Somehow my [load_ico](https://github.com/TornaxO7/vimico/blob/main/__init__.py#L24r function doesn't get loaded although [`test_ico`](https://github.com/TornaxO7/vimico/blob/main/__init__.py#L15) returns `True`. Do you have an idea why it doesn't work?

**Comment by TornaxO7** [comment]
Oh, wait no, it works!
![image](https://user-images.githubusercontent.com/50843046/162580153-88401585-48f8-4cd7-817d-98afef2a6ea6.png)

Hm.... but if I start `vimiv`, I'm getting this:
![image](https://user-images.githubusercontent.com/50843046/162580168-2a075a82-2b43-4492-8bb3-677cb5b7404e.png)

then I have to select `cpu.ico` to see it :thinking:

**Comment by TornaxO7** [comment]
Ok wait, it looks like that I just need to add `test_ico` because the `.ico` is displayed without my `load_ico` function.

**Comment by TornaxO7** [comment]
could you show me the part where vimiv looks, if it can display the file on its own? It's probably easier to add the `.ico` support in vimiv since it's just a boolean check.

**Comment by jcjgraf** [comment]
That is all handled in `vimiv/utils/imagereader.py`

**Comment by TornaxO7** [comment]
Hm... ok I don't really understand, why it does work, could you please take a look at it?
https://github.com/TornaxO7/vimico/blob/main/__init__.py

**Comment by jcjgraf** [comment]
It seems like QImageReader supports ICO files, even though not listed [here](https://doc.qt.io/qtforpython/PySide6/QtGui/QImageReader.html?highlight=qimagereader#PySide6.QtGui.PySide6.QtGui.QImageReader.supportedImageFormats). So I enabled support for them in #487. Can you have a look at it and check if it works for you?
