### ISSUE TITLE
Feature Request: Sorting & Drag/Drop

### ISSUE THREAD

**Issue by anoduck** [karlch/vimiv-qt#500]
I have been on a quest now for several years to find an image viewer / image library manager that is lightweight, fast, and includes features expected of modern image viewers. This program comes very close to meeting all of these. It only lacks two features to make it superior to other applications. 

1. Drag and Drop - can be integrated with dragon to supply this.
2. Sorting - Very surprised this feature was not included from design.

**Comment by jcjgraf** [comment]
Great to hear that you like vimiv! And thanks for the feature requests

1. Drag & drop has been requested before (#455), but it has not been tackled yet. Could you elaborate how you would like the drap and drop feature? What is `dragon`?

2. I have implemented a sorting mechanism in #387. Due to missing testing it has not been merged yet. Since the owner of this repo is very busy and currently not available for review/feedback I am also not going to work on that soon. But feel free to check it out and give some feedback!

**Comment by anoduck** [comment]
@jcjgraf Dragon is a simple drag and drop solution for X and wayland. https://github.com/mwh/dragon

I use gthumb a lot to drag and drop photos from the file system to the browser to upload to sites, cloud storage, etc, etc... It would be unbelievably awesome if I could do this in thumbnail mode. This would allow me to race through the directory, grab the photo I want, and drag it to the browser for upload.

**Comment by jcjgraf** [comment]
Sorry for the long delay and thanks for the clarification. We wont we able to implement that soon, but we will keep this request in mind.

For your rather simple request, the following workaround may work:
1. Mark all images you want to drap&drop
2. Run `:!dragon-drop -A %m`
3. Drap&drop them to wherever you like

You can also bind that to a certain key.

Again, sorry that I cannot provide you with a better solution at the moment...

**Comment by anoduck** [comment]
No worries at all, we are all extremely busy these days. That works fine for me. As long as it can be done, I don't mind hacking up something. I am going to go ahead and close this one out. Thanks for the awesome software.
