### ISSUE TITLE
Returning to sorting images in vimiv.

### ISSUE THREAD

**Issue by anoduck** [karlch/vimiv-qt#523]
@jcjgraf Remember we talked earlier about sorting file in #500? Well, I didn't remember, went hunting for how to do it again, and found #386. I guess the light bulb didn't turn on, or the hamster stopped turning the wheel, but I didn't quite understand that you had already tackled this and committed changes to your own fork of vimiv-qt. 

So, what I am inquiring about is:
1. If I clone from your fork of vimiv-qt will I be able to then sort images?
2. If so, what branch has those changes? Would `master` work?
3. Is there anyway that functionality could be exported to a plugin to allow everyone to sort images regardless of which repo they cloned from?

-----

I did look into creating a drag and drop plugin for vimiv a few days ago, learned I would have to use one of the py-qt libraries to accomplish this. I believe it was pyside, but I am not sure if I remembered that correctly. Anyway, I went through the documentation a little before quitting for supper, and it seemed rather simple. Then again, the tasks that appear in the beginning to be simple, are the tasks that are bloody difficult to accomplish.

**Comment by jcjgraf** [comment]
Hey @anoduck

I am sorry that certain things are a bit a hassle and inconvenient to use. Sorting should be part of mainline vimiv for a long time, but due to multiple reasons it is not yet...
I have implemented the full sorting mechanism in #387 with multiple different orderings (see [here](https://github.com/karlch/vimiv-qt/pull/387#issuecomment-840512890) for a complete list of orderings).

1 & 2. You need to checkout my [feature branch](https://github.com/jcjgraf/vimiv-qt/tree/feature/ImageOrder). Alternatively, you can also checkout that pull request (as I described [here](https://github.com/karlch/vimiv-qt/issues/386#issuecomment-860544397))
3. As said, it should get merged into vimiv sometime. Ordering is a core part and should not go into a plugin. I have rebased my feature branch to vimiv master, to make sure you have the "latest-and-greatest" changes (well, there are probably not too many 😬)

Great to hear that you have looked into the drag-and-drop functionality! I could imagine that it is much simple to directly implement that in vimiv instead of a separate plugin. And I wold also argue that it makes sense to have this functionality directly in vimiv (as long as it does not introduce any overhead or large amount of code). New dependencies should be optional, meaning that this feature is disabled when the dependencies are not met. Though, I do not know @karlch's opinion on the mapper.

Anyways, let me know if you achieve anything or you need any help with that, and sorry for the hassle with the open PRs!

**Comment by anoduck** [comment]
No Worries. You're too nice. 

I gotcha, pulling it now and building.
