### ISSUE TITLE
suggestion: open a URL

### ISSUE THREAD

**Issue by elig0n** [karlch/vimiv-qt#678]
it can be useful to be able to open URLs directly, i.e.:

`vimiv https://i.imgur.com/somefile.png`

**Comment by karlch** [comment]
Thanks for your thoughts!

Another, not so sure about this. With #459, you could just run `curl https://i.imgur.com/somefile.png | vimiv -`, is this sufficient for your use-cases?

Otherwise, we would have to extend `:open` to be able to:
1. Check if strings are urls
2. If yes, download and store to a tempfile
3. Continue working with the tempfile
