### ISSUE TITLE
`<escape>` and `del` bindings don't work?

### ISSUE THREAD

**Issue by xfzv** [karlch/vimiv-qt#682]
I'm trying to bind the `<escape>` and `del` keys in `keys.conf`, but they don't work for any command.

```console
❯ vimiv --version
vimiv v0.9.0

Python: 3.11.3
Qt: 5.15.8
PyQt: 5.15.9

Svg Support: True


Paths:
cache: /home/xfzv/.cache/vimiv
config: /home/xfzv/.config/vimiv
data: /home/xfzv/.local/share/vimiv
```

I installed `vimiv-qt` via [`vimviv-qt` (AUR)](https://aur.archlinux.org/packages/vimiv-qt).

- `~/.config/vimiv/keys.conf`

```console
[GLOBAL]
q : quit            # default - works
<escape> : quit     # doesn't work

[IMAGE]
dD : delete --ask %%    # works
del : delete --ask %%   # doesn't work

<end> : goto -1     # default - works
del : goto -1       # doesn't work

[COMMAND]
<escape> : leave-commandline    # default - works
```

I found <https://github.com/karlch/vimiv-qt/blob/036e41561456387d8b11895ca9a45428563007aa/vimiv/gui/eventhandler.py#L131-L137> regarding the `<escape>` key, maybe that's a limitation?

I couldn't find anything about `del` key though, I assume it should work. Both keys seem to be detected fine with `--debug gui.eventhandler`:

```console
❯ vimiv --debug gui.eventhandler
[..]
[12:10:10] DEBUG    <gui.eventhandler>   KeyPressEvent: handling <escape> key specially
[12:10:13] DEBUG    <gui.eventhandler>   EventHandlerMixin: handling del for mode image
[12:10:13] DEBUG    <gui.eventhandler>   EventHandlerMixin: no matches for event
```

**Comment by karlch** [comment]
Thanks for catching this!

`<escape>` is currently a limitation, you are right, as it is hard-coded exactly like you found.

`del` doesn't work because vimiv interprets this as `d` `e` `l` in sequence. It should be added to the  `special_keys` dict in `gui.eventhandler` like so:
```python
        Qt.Key_Delete: "<delete>",
```
and then one can bind `<delete>` instead and it should work just fine :blush: 

Feel free to open a PR if you like, as you did all the debugging, otherwise I'll try to commit sometime later. I'll be offline for most of the week-end unfortunately.

**Comment by karlch** [comment]
Perfect, thanks for the PR!

Not so sure about `<escape>`. This should be rather trivial code-wise, but what other key would you then use for "generic cancel"? Is it possible to re-bind `<escape>` in `vim`?

**Comment by karlch** [comment]
So in principal it is up to the user, to ensure this behaviour is somehow mapped? That is definitely trivial to do also on our side.
