### ISSUE TITLE
Force reload?

### ISSUE THREAD

**Issue by niksingh710** [karlch/vimiv-qt#820]
Any way to force reload thumbnail view?

As I have marked a few images and then deleted them using the cmd `delete %m` they are still in the view till I reopen vimiv. Any way to force reload that without reopening?

**Comment by jcjgraf** [comment]
There is not way to force reload the thumbnail view. That is because it reloads it automatically whenever something changed in the opened directory. Possibly the file watcher is not working properly for you.

Could you provide your system information, output of `vimiv -v`, and the debug logs of when this issue happens (start vimiv using `vimiv --log-level DEBUG`).

Please delete the duplicate issue that you created #821

**Comment by niksingh710** [comment]
okay so it is working if i am using it a dir.
but if i do like `vimiv ./**/*/*` then it delete's it successfully but does not update thumbnail.

```
vimiv v0.9.0

Python: 3.12.3
Qt: 5.15.13
PyQt: 5.15.10

Svg Support: True


Paths:
cache: /home/niksingh710/.cache/vimiv
config: /home/niksingh710/.config/vimiv
data: /home/niksingh710/.local/share/vimiv
```

https://gist.github.com/niksingh710/dc752b326be15c014843cb6f49263c21

**Comment by karlch** [comment]
This is unfortunately a known issue and part of #299.

> only images in the directory of the first image are tracked by the working directory handler. Therefore deleting/changing any of the other images is not communicated back to vimiv.

I would definitely prefer to fix this directly in the working directory handler instead of adding some sort of a forced reload. Reading over `QFileSystemWatcher`, it should support watching multiple directories. So we could in principle also watch more than one directory (at the corresponding cost), but would then also need to update our trivial logic of "just reload the current directory". As time is really the main constraint at the moment, not sure how soon this would happen.

**Comment by niksingh710** [comment]
Yep, it makes sense to fix the watcher.
Will be closing this in favor of #299
