### ISSUE TITLE
Camera integration

### ISSUE THREAD

**Issue by karlch** [karlch/vimiv-qt#83]
It would be nice to have some sort of integration with cameras to e.g. import all files from the camera. This is probably rather heavy and should be implemented as a plugin as it almost certainly comes with additional dependencies.

**Comment by jcjgraf** [comment]
I have created [Importer](https://github.com/jcjgraf/Importer). It lets you easily import images from a SD card, camera or any directory into your photo storage. The importer obeys your desired storage directory structure and image naming scheme.

I would not call in camera integration (this sounds rather like tethering or something) but it does pretty much what you have described.

I have textet you @karlch concerning this plugin some months ago but it has somehow passed into oblivion. You had some points which I want to quickly address here:

> How do you open the pictures considered for in vimiv in the first place? If I mount my SD card, the images are all over the place in various subfolders, so this would involve something fancy like :open **/*.jpg or so.
- I do not really have this problem, but I do get your point. But I my view this functionality is also useful in situations not related to importing. Lets say you were on a one week trip and the images are put in folders by days and you want to give someone an impression of this trip. Obviously, you can open them day by day, but in order to get a complete overview I really like to have them open all at once. All in all, in my opinion this functionality should get added to vimiv itself (or a seperate plugin).

> Would an option to add an identifier string be interesting? I tend to structure my images in the form Y/m-Identifier where Identifier could be something like SummerHoliday.
- Makes sense, I have added this.


P.S. Happy new year! :partying_face:

**Comment by karlch** [comment]
This is awesome, thanks a lot for sharing this! I have added it to the [user plugins section](https://karlch.github.io/vimiv-qt/documentation/configuration/plugins.html) of the documentation along with `BatchMark`.

In principle the syntax I mentioned works just fine, i.e. `:open **/*.jpg` does what one would expect, I was not sure this is what you do as I find it a bit messy :blush:

Minor note so we don't forget: the exif part will have to be changed once we merge the new code.

A happy new year to you too! :tada:

**Comment by jcjgraf** [comment]
Oh, in this case I have misunderstood you. And good to know that this glob expansion works for vimiv :blush:

Would you find it useful to have an option like `:importer --all-subdir` which imports all images found in subdirectories of the CWD? Personally, I do not have a use case for such an option (at least not as long as there is not option do detect already imported images), because I do not erase my SD cards after importing images. I leave all images on the card till I run out of space. Only then I format it :smiley: 

But if this is something which you would find useful I am very keen on adding such an option.

**Comment by karlch** [comment]
I don't think the option you propose is worth the additional effort, it is equivalent to something along `:mark **/*` and then just calling `:importer` which doesn't seem too difficult for something one would rarely do.

The option to detect already imported images would be amazing of course. I also rarely delete images from the SD cards, but sounds like it would need quite some thinking and work :smile:

**Comment by jcjgraf** [comment]
A rudimentary (but very fast) implementation for a duplicate detection could do a metadata comparison (e.g. file size) upon a naming conflict (when importer tries to copy an image to a destination which does already exist). Obviously, this does only work when one does strictly stick to the chosen naming scheme as well as one does not editing the original image files. This would probably work for my use case but there may be a more sophisticated solution :smile:

**Comment by karlch** [comment]
Closing - Importer is a nice working plugin that possibly be extended, but I don't see this ending up in mainline vimiv. Wonderful showcase of what plugins are capable of though :blush:
